// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Encapsulate.proto

package com.example.vertbuff;

public final class PersonProto {
  private PersonProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonReportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person.PersonReport)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 person_id = 1;</code>
     */
    int getPersonId();

    /**
     * <code>int32 age = 2;</code>
     */
    int getAge();

    /**
     * <code>int64 height = 3;</code>
     */
    long getHeight();

    /**
     * <code>string classification = 4;</code>
     */
    java.lang.String getClassification();
    /**
     * <code>string classification = 4;</code>
     */
    com.google.protobuf.ByteString
        getClassificationBytes();
  }
  /**
   * Protobuf type {@code Person.PersonReport}
   */
  public  static final class PersonReport extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person.PersonReport)
      PersonReportOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PersonReport.newBuilder() to construct.
    private PersonReport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PersonReport() {
      personId_ = 0;
      age_ = 0;
      height_ = 0L;
      classification_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PersonReport(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              personId_ = input.readInt32();
              break;
            }
            case 16: {

              age_ = input.readInt32();
              break;
            }
            case 24: {

              height_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              classification_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.vertbuff.PersonProto.internal_static_Person_PersonReport_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.vertbuff.PersonProto.internal_static_Person_PersonReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.vertbuff.PersonProto.PersonReport.class, com.example.vertbuff.PersonProto.PersonReport.Builder.class);
    }

    public static final int PERSON_ID_FIELD_NUMBER = 1;
    private int personId_;
    /**
     * <code>int32 person_id = 1;</code>
     */
    public int getPersonId() {
      return personId_;
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <code>int32 age = 2;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private long height_;
    /**
     * <code>int64 height = 3;</code>
     */
    public long getHeight() {
      return height_;
    }

    public static final int CLASSIFICATION_FIELD_NUMBER = 4;
    private volatile java.lang.Object classification_;
    /**
     * <code>string classification = 4;</code>
     */
    public java.lang.String getClassification() {
      java.lang.Object ref = classification_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        classification_ = s;
        return s;
      }
    }
    /**
     * <code>string classification = 4;</code>
     */
    public com.google.protobuf.ByteString
        getClassificationBytes() {
      java.lang.Object ref = classification_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        classification_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (personId_ != 0) {
        output.writeInt32(1, personId_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      if (height_ != 0L) {
        output.writeInt64(3, height_);
      }
      if (!getClassificationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, classification_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (personId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, personId_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      if (height_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, height_);
      }
      if (!getClassificationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, classification_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.vertbuff.PersonProto.PersonReport)) {
        return super.equals(obj);
      }
      com.example.vertbuff.PersonProto.PersonReport other = (com.example.vertbuff.PersonProto.PersonReport) obj;

      boolean result = true;
      result = result && (getPersonId()
          == other.getPersonId());
      result = result && (getAge()
          == other.getAge());
      result = result && (getHeight()
          == other.getHeight());
      result = result && getClassification()
          .equals(other.getClassification());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PERSON_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPersonId();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHeight());
      hash = (37 * hash) + CLASSIFICATION_FIELD_NUMBER;
      hash = (53 * hash) + getClassification().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.vertbuff.PersonProto.PersonReport parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.vertbuff.PersonProto.PersonReport parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.PersonReport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.vertbuff.PersonProto.PersonReport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.PersonReport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.vertbuff.PersonProto.PersonReport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.PersonReport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.vertbuff.PersonProto.PersonReport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.PersonReport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.vertbuff.PersonProto.PersonReport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.PersonReport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.vertbuff.PersonProto.PersonReport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.vertbuff.PersonProto.PersonReport prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person.PersonReport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person.PersonReport)
        com.example.vertbuff.PersonProto.PersonReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.vertbuff.PersonProto.internal_static_Person_PersonReport_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.vertbuff.PersonProto.internal_static_Person_PersonReport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.vertbuff.PersonProto.PersonReport.class, com.example.vertbuff.PersonProto.PersonReport.Builder.class);
      }

      // Construct using com.example.vertbuff.PersonProto.PersonReport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        personId_ = 0;

        age_ = 0;

        height_ = 0L;

        classification_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.vertbuff.PersonProto.internal_static_Person_PersonReport_descriptor;
      }

      public com.example.vertbuff.PersonProto.PersonReport getDefaultInstanceForType() {
        return com.example.vertbuff.PersonProto.PersonReport.getDefaultInstance();
      }

      public com.example.vertbuff.PersonProto.PersonReport build() {
        com.example.vertbuff.PersonProto.PersonReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.vertbuff.PersonProto.PersonReport buildPartial() {
        com.example.vertbuff.PersonProto.PersonReport result = new com.example.vertbuff.PersonProto.PersonReport(this);
        result.personId_ = personId_;
        result.age_ = age_;
        result.height_ = height_;
        result.classification_ = classification_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.vertbuff.PersonProto.PersonReport) {
          return mergeFrom((com.example.vertbuff.PersonProto.PersonReport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.vertbuff.PersonProto.PersonReport other) {
        if (other == com.example.vertbuff.PersonProto.PersonReport.getDefaultInstance()) return this;
        if (other.getPersonId() != 0) {
          setPersonId(other.getPersonId());
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getHeight() != 0L) {
          setHeight(other.getHeight());
        }
        if (!other.getClassification().isEmpty()) {
          classification_ = other.classification_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.vertbuff.PersonProto.PersonReport parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.vertbuff.PersonProto.PersonReport) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int personId_ ;
      /**
       * <code>int32 person_id = 1;</code>
       */
      public int getPersonId() {
        return personId_;
      }
      /**
       * <code>int32 person_id = 1;</code>
       */
      public Builder setPersonId(int value) {
        
        personId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 person_id = 1;</code>
       */
      public Builder clearPersonId() {
        
        personId_ = 0;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 2;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 2;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 2;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private long height_ ;
      /**
       * <code>int64 height = 3;</code>
       */
      public long getHeight() {
        return height_;
      }
      /**
       * <code>int64 height = 3;</code>
       */
      public Builder setHeight(long value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 height = 3;</code>
       */
      public Builder clearHeight() {
        
        height_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object classification_ = "";
      /**
       * <code>string classification = 4;</code>
       */
      public java.lang.String getClassification() {
        java.lang.Object ref = classification_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          classification_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string classification = 4;</code>
       */
      public com.google.protobuf.ByteString
          getClassificationBytes() {
        java.lang.Object ref = classification_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          classification_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string classification = 4;</code>
       */
      public Builder setClassification(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        classification_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string classification = 4;</code>
       */
      public Builder clearClassification() {
        
        classification_ = getDefaultInstance().getClassification();
        onChanged();
        return this;
      }
      /**
       * <code>string classification = 4;</code>
       */
      public Builder setClassificationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        classification_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Person.PersonReport)
    }

    // @@protoc_insertion_point(class_scope:Person.PersonReport)
    private static final com.example.vertbuff.PersonProto.PersonReport DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.vertbuff.PersonProto.PersonReport();
    }

    public static com.example.vertbuff.PersonProto.PersonReport getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PersonReport>
        PARSER = new com.google.protobuf.AbstractParser<PersonReport>() {
      public PersonReport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PersonReport(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PersonReport> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PersonReport> getParserForType() {
      return PARSER;
    }

    public com.example.vertbuff.PersonProto.PersonReport getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LocationReportOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person.LocationReport)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 Location_id = 1;</code>
     */
    int getLocationId();

    /**
     * <code>int64 x = 2;</code>
     */
    long getX();

    /**
     * <code>int32 Location_type = 3;</code>
     */
    int getLocationType();
  }
  /**
   * Protobuf type {@code Person.LocationReport}
   */
  public  static final class LocationReport extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person.LocationReport)
      LocationReportOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use LocationReport.newBuilder() to construct.
    private LocationReport(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LocationReport() {
      locationId_ = 0;
      x_ = 0L;
      locationType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private LocationReport(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              locationId_ = input.readInt32();
              break;
            }
            case 16: {

              x_ = input.readInt64();
              break;
            }
            case 24: {

              locationType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.vertbuff.PersonProto.internal_static_Person_LocationReport_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.vertbuff.PersonProto.internal_static_Person_LocationReport_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.vertbuff.PersonProto.LocationReport.class, com.example.vertbuff.PersonProto.LocationReport.Builder.class);
    }

    public static final int LOCATION_ID_FIELD_NUMBER = 1;
    private int locationId_;
    /**
     * <code>int32 Location_id = 1;</code>
     */
    public int getLocationId() {
      return locationId_;
    }

    public static final int X_FIELD_NUMBER = 2;
    private long x_;
    /**
     * <code>int64 x = 2;</code>
     */
    public long getX() {
      return x_;
    }

    public static final int LOCATION_TYPE_FIELD_NUMBER = 3;
    private int locationType_;
    /**
     * <code>int32 Location_type = 3;</code>
     */
    public int getLocationType() {
      return locationType_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (locationId_ != 0) {
        output.writeInt32(1, locationId_);
      }
      if (x_ != 0L) {
        output.writeInt64(2, x_);
      }
      if (locationType_ != 0) {
        output.writeInt32(3, locationType_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (locationId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, locationId_);
      }
      if (x_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, x_);
      }
      if (locationType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, locationType_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.vertbuff.PersonProto.LocationReport)) {
        return super.equals(obj);
      }
      com.example.vertbuff.PersonProto.LocationReport other = (com.example.vertbuff.PersonProto.LocationReport) obj;

      boolean result = true;
      result = result && (getLocationId()
          == other.getLocationId());
      result = result && (getX()
          == other.getX());
      result = result && (getLocationType()
          == other.getLocationType());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOCATION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getLocationId();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getX());
      hash = (37 * hash) + LOCATION_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getLocationType();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.vertbuff.PersonProto.LocationReport parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.vertbuff.PersonProto.LocationReport parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.LocationReport parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.vertbuff.PersonProto.LocationReport parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.LocationReport parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.vertbuff.PersonProto.LocationReport parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.LocationReport parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.vertbuff.PersonProto.LocationReport parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.LocationReport parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.vertbuff.PersonProto.LocationReport parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.LocationReport parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.vertbuff.PersonProto.LocationReport parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.vertbuff.PersonProto.LocationReport prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person.LocationReport}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person.LocationReport)
        com.example.vertbuff.PersonProto.LocationReportOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.vertbuff.PersonProto.internal_static_Person_LocationReport_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.vertbuff.PersonProto.internal_static_Person_LocationReport_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.vertbuff.PersonProto.LocationReport.class, com.example.vertbuff.PersonProto.LocationReport.Builder.class);
      }

      // Construct using com.example.vertbuff.PersonProto.LocationReport.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        locationId_ = 0;

        x_ = 0L;

        locationType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.vertbuff.PersonProto.internal_static_Person_LocationReport_descriptor;
      }

      public com.example.vertbuff.PersonProto.LocationReport getDefaultInstanceForType() {
        return com.example.vertbuff.PersonProto.LocationReport.getDefaultInstance();
      }

      public com.example.vertbuff.PersonProto.LocationReport build() {
        com.example.vertbuff.PersonProto.LocationReport result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.vertbuff.PersonProto.LocationReport buildPartial() {
        com.example.vertbuff.PersonProto.LocationReport result = new com.example.vertbuff.PersonProto.LocationReport(this);
        result.locationId_ = locationId_;
        result.x_ = x_;
        result.locationType_ = locationType_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.vertbuff.PersonProto.LocationReport) {
          return mergeFrom((com.example.vertbuff.PersonProto.LocationReport)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.vertbuff.PersonProto.LocationReport other) {
        if (other == com.example.vertbuff.PersonProto.LocationReport.getDefaultInstance()) return this;
        if (other.getLocationId() != 0) {
          setLocationId(other.getLocationId());
        }
        if (other.getX() != 0L) {
          setX(other.getX());
        }
        if (other.getLocationType() != 0) {
          setLocationType(other.getLocationType());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.vertbuff.PersonProto.LocationReport parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.vertbuff.PersonProto.LocationReport) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int locationId_ ;
      /**
       * <code>int32 Location_id = 1;</code>
       */
      public int getLocationId() {
        return locationId_;
      }
      /**
       * <code>int32 Location_id = 1;</code>
       */
      public Builder setLocationId(int value) {
        
        locationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Location_id = 1;</code>
       */
      public Builder clearLocationId() {
        
        locationId_ = 0;
        onChanged();
        return this;
      }

      private long x_ ;
      /**
       * <code>int64 x = 2;</code>
       */
      public long getX() {
        return x_;
      }
      /**
       * <code>int64 x = 2;</code>
       */
      public Builder setX(long value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 x = 2;</code>
       */
      public Builder clearX() {
        
        x_ = 0L;
        onChanged();
        return this;
      }

      private int locationType_ ;
      /**
       * <code>int32 Location_type = 3;</code>
       */
      public int getLocationType() {
        return locationType_;
      }
      /**
       * <code>int32 Location_type = 3;</code>
       */
      public Builder setLocationType(int value) {
        
        locationType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Location_type = 3;</code>
       */
      public Builder clearLocationType() {
        
        locationType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Person.LocationReport)
    }

    // @@protoc_insertion_point(class_scope:Person.LocationReport)
    private static final com.example.vertbuff.PersonProto.LocationReport DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.vertbuff.PersonProto.LocationReport();
    }

    public static com.example.vertbuff.PersonProto.LocationReport getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LocationReport>
        PARSER = new com.google.protobuf.AbstractParser<LocationReport>() {
      public LocationReport parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LocationReport(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LocationReport> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LocationReport> getParserForType() {
      return PARSER;
    }

    public com.example.vertbuff.PersonProto.LocationReport getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CommunicationMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Person.CommunicationMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 msgid = 1;</code>
     */
    long getMsgid();

    /**
     * <code>.Person.PersonReport PersonReport = 2;</code>
     */
    boolean hasPersonReport();
    /**
     * <code>.Person.PersonReport PersonReport = 2;</code>
     */
    com.example.vertbuff.PersonProto.PersonReport getPersonReport();
    /**
     * <code>.Person.PersonReport PersonReport = 2;</code>
     */
    com.example.vertbuff.PersonProto.PersonReportOrBuilder getPersonReportOrBuilder();

    /**
     * <code>.Person.LocationReport LocationReport = 3;</code>
     */
    boolean hasLocationReport();
    /**
     * <code>.Person.LocationReport LocationReport = 3;</code>
     */
    com.example.vertbuff.PersonProto.LocationReport getLocationReport();
    /**
     * <code>.Person.LocationReport LocationReport = 3;</code>
     */
    com.example.vertbuff.PersonProto.LocationReportOrBuilder getLocationReportOrBuilder();

    public com.example.vertbuff.PersonProto.CommunicationMessage.BodyCase getBodyCase();
  }
  /**
   * Protobuf type {@code Person.CommunicationMessage}
   */
  public  static final class CommunicationMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Person.CommunicationMessage)
      CommunicationMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CommunicationMessage.newBuilder() to construct.
    private CommunicationMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CommunicationMessage() {
      msgid_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CommunicationMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              msgid_ = input.readInt64();
              break;
            }
            case 18: {
              com.example.vertbuff.PersonProto.PersonReport.Builder subBuilder = null;
              if (bodyCase_ == 2) {
                subBuilder = ((com.example.vertbuff.PersonProto.PersonReport) body_).toBuilder();
              }
              body_ =
                  input.readMessage(com.example.vertbuff.PersonProto.PersonReport.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.example.vertbuff.PersonProto.PersonReport) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 2;
              break;
            }
            case 26: {
              com.example.vertbuff.PersonProto.LocationReport.Builder subBuilder = null;
              if (bodyCase_ == 3) {
                subBuilder = ((com.example.vertbuff.PersonProto.LocationReport) body_).toBuilder();
              }
              body_ =
                  input.readMessage(com.example.vertbuff.PersonProto.LocationReport.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.example.vertbuff.PersonProto.LocationReport) body_);
                body_ = subBuilder.buildPartial();
              }
              bodyCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.vertbuff.PersonProto.internal_static_Person_CommunicationMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.vertbuff.PersonProto.internal_static_Person_CommunicationMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.vertbuff.PersonProto.CommunicationMessage.class, com.example.vertbuff.PersonProto.CommunicationMessage.Builder.class);
    }

    private int bodyCase_ = 0;
    private java.lang.Object body_;
    public enum BodyCase
        implements com.google.protobuf.Internal.EnumLite {
      PERSONREPORT(2),
      LOCATIONREPORT(3),
      BODY_NOT_SET(0);
      private final int value;
      private BodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static BodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static BodyCase forNumber(int value) {
        switch (value) {
          case 2: return PERSONREPORT;
          case 3: return LOCATIONREPORT;
          case 0: return BODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public BodyCase
    getBodyCase() {
      return BodyCase.forNumber(
          bodyCase_);
    }

    public static final int MSGID_FIELD_NUMBER = 1;
    private long msgid_;
    /**
     * <code>int64 msgid = 1;</code>
     */
    public long getMsgid() {
      return msgid_;
    }

    public static final int PERSONREPORT_FIELD_NUMBER = 2;
    /**
     * <code>.Person.PersonReport PersonReport = 2;</code>
     */
    public boolean hasPersonReport() {
      return bodyCase_ == 2;
    }
    /**
     * <code>.Person.PersonReport PersonReport = 2;</code>
     */
    public com.example.vertbuff.PersonProto.PersonReport getPersonReport() {
      if (bodyCase_ == 2) {
         return (com.example.vertbuff.PersonProto.PersonReport) body_;
      }
      return com.example.vertbuff.PersonProto.PersonReport.getDefaultInstance();
    }
    /**
     * <code>.Person.PersonReport PersonReport = 2;</code>
     */
    public com.example.vertbuff.PersonProto.PersonReportOrBuilder getPersonReportOrBuilder() {
      if (bodyCase_ == 2) {
         return (com.example.vertbuff.PersonProto.PersonReport) body_;
      }
      return com.example.vertbuff.PersonProto.PersonReport.getDefaultInstance();
    }

    public static final int LOCATIONREPORT_FIELD_NUMBER = 3;
    /**
     * <code>.Person.LocationReport LocationReport = 3;</code>
     */
    public boolean hasLocationReport() {
      return bodyCase_ == 3;
    }
    /**
     * <code>.Person.LocationReport LocationReport = 3;</code>
     */
    public com.example.vertbuff.PersonProto.LocationReport getLocationReport() {
      if (bodyCase_ == 3) {
         return (com.example.vertbuff.PersonProto.LocationReport) body_;
      }
      return com.example.vertbuff.PersonProto.LocationReport.getDefaultInstance();
    }
    /**
     * <code>.Person.LocationReport LocationReport = 3;</code>
     */
    public com.example.vertbuff.PersonProto.LocationReportOrBuilder getLocationReportOrBuilder() {
      if (bodyCase_ == 3) {
         return (com.example.vertbuff.PersonProto.LocationReport) body_;
      }
      return com.example.vertbuff.PersonProto.LocationReport.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (msgid_ != 0L) {
        output.writeInt64(1, msgid_);
      }
      if (bodyCase_ == 2) {
        output.writeMessage(2, (com.example.vertbuff.PersonProto.PersonReport) body_);
      }
      if (bodyCase_ == 3) {
        output.writeMessage(3, (com.example.vertbuff.PersonProto.LocationReport) body_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (msgid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, msgid_);
      }
      if (bodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (com.example.vertbuff.PersonProto.PersonReport) body_);
      }
      if (bodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (com.example.vertbuff.PersonProto.LocationReport) body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.vertbuff.PersonProto.CommunicationMessage)) {
        return super.equals(obj);
      }
      com.example.vertbuff.PersonProto.CommunicationMessage other = (com.example.vertbuff.PersonProto.CommunicationMessage) obj;

      boolean result = true;
      result = result && (getMsgid()
          == other.getMsgid());
      result = result && getBodyCase().equals(
          other.getBodyCase());
      if (!result) return false;
      switch (bodyCase_) {
        case 2:
          result = result && getPersonReport()
              .equals(other.getPersonReport());
          break;
        case 3:
          result = result && getLocationReport()
              .equals(other.getLocationReport());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgid());
      switch (bodyCase_) {
        case 2:
          hash = (37 * hash) + PERSONREPORT_FIELD_NUMBER;
          hash = (53 * hash) + getPersonReport().hashCode();
          break;
        case 3:
          hash = (37 * hash) + LOCATIONREPORT_FIELD_NUMBER;
          hash = (53 * hash) + getLocationReport().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.vertbuff.PersonProto.CommunicationMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.vertbuff.PersonProto.CommunicationMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.CommunicationMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.vertbuff.PersonProto.CommunicationMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.CommunicationMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.vertbuff.PersonProto.CommunicationMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.CommunicationMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.vertbuff.PersonProto.CommunicationMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.CommunicationMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.vertbuff.PersonProto.CommunicationMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.vertbuff.PersonProto.CommunicationMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.vertbuff.PersonProto.CommunicationMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.vertbuff.PersonProto.CommunicationMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Person.CommunicationMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Person.CommunicationMessage)
        com.example.vertbuff.PersonProto.CommunicationMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.vertbuff.PersonProto.internal_static_Person_CommunicationMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.vertbuff.PersonProto.internal_static_Person_CommunicationMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.vertbuff.PersonProto.CommunicationMessage.class, com.example.vertbuff.PersonProto.CommunicationMessage.Builder.class);
      }

      // Construct using com.example.vertbuff.PersonProto.CommunicationMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        msgid_ = 0L;

        bodyCase_ = 0;
        body_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.vertbuff.PersonProto.internal_static_Person_CommunicationMessage_descriptor;
      }

      public com.example.vertbuff.PersonProto.CommunicationMessage getDefaultInstanceForType() {
        return com.example.vertbuff.PersonProto.CommunicationMessage.getDefaultInstance();
      }

      public com.example.vertbuff.PersonProto.CommunicationMessage build() {
        com.example.vertbuff.PersonProto.CommunicationMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.vertbuff.PersonProto.CommunicationMessage buildPartial() {
        com.example.vertbuff.PersonProto.CommunicationMessage result = new com.example.vertbuff.PersonProto.CommunicationMessage(this);
        result.msgid_ = msgid_;
        if (bodyCase_ == 2) {
          if (personReportBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = personReportBuilder_.build();
          }
        }
        if (bodyCase_ == 3) {
          if (locationReportBuilder_ == null) {
            result.body_ = body_;
          } else {
            result.body_ = locationReportBuilder_.build();
          }
        }
        result.bodyCase_ = bodyCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.vertbuff.PersonProto.CommunicationMessage) {
          return mergeFrom((com.example.vertbuff.PersonProto.CommunicationMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.vertbuff.PersonProto.CommunicationMessage other) {
        if (other == com.example.vertbuff.PersonProto.CommunicationMessage.getDefaultInstance()) return this;
        if (other.getMsgid() != 0L) {
          setMsgid(other.getMsgid());
        }
        switch (other.getBodyCase()) {
          case PERSONREPORT: {
            mergePersonReport(other.getPersonReport());
            break;
          }
          case LOCATIONREPORT: {
            mergeLocationReport(other.getLocationReport());
            break;
          }
          case BODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.vertbuff.PersonProto.CommunicationMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.vertbuff.PersonProto.CommunicationMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bodyCase_ = 0;
      private java.lang.Object body_;
      public BodyCase
          getBodyCase() {
        return BodyCase.forNumber(
            bodyCase_);
      }

      public Builder clearBody() {
        bodyCase_ = 0;
        body_ = null;
        onChanged();
        return this;
      }


      private long msgid_ ;
      /**
       * <code>int64 msgid = 1;</code>
       */
      public long getMsgid() {
        return msgid_;
      }
      /**
       * <code>int64 msgid = 1;</code>
       */
      public Builder setMsgid(long value) {
        
        msgid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 msgid = 1;</code>
       */
      public Builder clearMsgid() {
        
        msgid_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.vertbuff.PersonProto.PersonReport, com.example.vertbuff.PersonProto.PersonReport.Builder, com.example.vertbuff.PersonProto.PersonReportOrBuilder> personReportBuilder_;
      /**
       * <code>.Person.PersonReport PersonReport = 2;</code>
       */
      public boolean hasPersonReport() {
        return bodyCase_ == 2;
      }
      /**
       * <code>.Person.PersonReport PersonReport = 2;</code>
       */
      public com.example.vertbuff.PersonProto.PersonReport getPersonReport() {
        if (personReportBuilder_ == null) {
          if (bodyCase_ == 2) {
            return (com.example.vertbuff.PersonProto.PersonReport) body_;
          }
          return com.example.vertbuff.PersonProto.PersonReport.getDefaultInstance();
        } else {
          if (bodyCase_ == 2) {
            return personReportBuilder_.getMessage();
          }
          return com.example.vertbuff.PersonProto.PersonReport.getDefaultInstance();
        }
      }
      /**
       * <code>.Person.PersonReport PersonReport = 2;</code>
       */
      public Builder setPersonReport(com.example.vertbuff.PersonProto.PersonReport value) {
        if (personReportBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          personReportBuilder_.setMessage(value);
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Person.PersonReport PersonReport = 2;</code>
       */
      public Builder setPersonReport(
          com.example.vertbuff.PersonProto.PersonReport.Builder builderForValue) {
        if (personReportBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          personReportBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Person.PersonReport PersonReport = 2;</code>
       */
      public Builder mergePersonReport(com.example.vertbuff.PersonProto.PersonReport value) {
        if (personReportBuilder_ == null) {
          if (bodyCase_ == 2 &&
              body_ != com.example.vertbuff.PersonProto.PersonReport.getDefaultInstance()) {
            body_ = com.example.vertbuff.PersonProto.PersonReport.newBuilder((com.example.vertbuff.PersonProto.PersonReport) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 2) {
            personReportBuilder_.mergeFrom(value);
          }
          personReportBuilder_.setMessage(value);
        }
        bodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Person.PersonReport PersonReport = 2;</code>
       */
      public Builder clearPersonReport() {
        if (personReportBuilder_ == null) {
          if (bodyCase_ == 2) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 2) {
            bodyCase_ = 0;
            body_ = null;
          }
          personReportBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Person.PersonReport PersonReport = 2;</code>
       */
      public com.example.vertbuff.PersonProto.PersonReport.Builder getPersonReportBuilder() {
        return getPersonReportFieldBuilder().getBuilder();
      }
      /**
       * <code>.Person.PersonReport PersonReport = 2;</code>
       */
      public com.example.vertbuff.PersonProto.PersonReportOrBuilder getPersonReportOrBuilder() {
        if ((bodyCase_ == 2) && (personReportBuilder_ != null)) {
          return personReportBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 2) {
            return (com.example.vertbuff.PersonProto.PersonReport) body_;
          }
          return com.example.vertbuff.PersonProto.PersonReport.getDefaultInstance();
        }
      }
      /**
       * <code>.Person.PersonReport PersonReport = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.vertbuff.PersonProto.PersonReport, com.example.vertbuff.PersonProto.PersonReport.Builder, com.example.vertbuff.PersonProto.PersonReportOrBuilder> 
          getPersonReportFieldBuilder() {
        if (personReportBuilder_ == null) {
          if (!(bodyCase_ == 2)) {
            body_ = com.example.vertbuff.PersonProto.PersonReport.getDefaultInstance();
          }
          personReportBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.example.vertbuff.PersonProto.PersonReport, com.example.vertbuff.PersonProto.PersonReport.Builder, com.example.vertbuff.PersonProto.PersonReportOrBuilder>(
                  (com.example.vertbuff.PersonProto.PersonReport) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 2;
        onChanged();;
        return personReportBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.vertbuff.PersonProto.LocationReport, com.example.vertbuff.PersonProto.LocationReport.Builder, com.example.vertbuff.PersonProto.LocationReportOrBuilder> locationReportBuilder_;
      /**
       * <code>.Person.LocationReport LocationReport = 3;</code>
       */
      public boolean hasLocationReport() {
        return bodyCase_ == 3;
      }
      /**
       * <code>.Person.LocationReport LocationReport = 3;</code>
       */
      public com.example.vertbuff.PersonProto.LocationReport getLocationReport() {
        if (locationReportBuilder_ == null) {
          if (bodyCase_ == 3) {
            return (com.example.vertbuff.PersonProto.LocationReport) body_;
          }
          return com.example.vertbuff.PersonProto.LocationReport.getDefaultInstance();
        } else {
          if (bodyCase_ == 3) {
            return locationReportBuilder_.getMessage();
          }
          return com.example.vertbuff.PersonProto.LocationReport.getDefaultInstance();
        }
      }
      /**
       * <code>.Person.LocationReport LocationReport = 3;</code>
       */
      public Builder setLocationReport(com.example.vertbuff.PersonProto.LocationReport value) {
        if (locationReportBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
          onChanged();
        } else {
          locationReportBuilder_.setMessage(value);
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Person.LocationReport LocationReport = 3;</code>
       */
      public Builder setLocationReport(
          com.example.vertbuff.PersonProto.LocationReport.Builder builderForValue) {
        if (locationReportBuilder_ == null) {
          body_ = builderForValue.build();
          onChanged();
        } else {
          locationReportBuilder_.setMessage(builderForValue.build());
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Person.LocationReport LocationReport = 3;</code>
       */
      public Builder mergeLocationReport(com.example.vertbuff.PersonProto.LocationReport value) {
        if (locationReportBuilder_ == null) {
          if (bodyCase_ == 3 &&
              body_ != com.example.vertbuff.PersonProto.LocationReport.getDefaultInstance()) {
            body_ = com.example.vertbuff.PersonProto.LocationReport.newBuilder((com.example.vertbuff.PersonProto.LocationReport) body_)
                .mergeFrom(value).buildPartial();
          } else {
            body_ = value;
          }
          onChanged();
        } else {
          if (bodyCase_ == 3) {
            locationReportBuilder_.mergeFrom(value);
          }
          locationReportBuilder_.setMessage(value);
        }
        bodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Person.LocationReport LocationReport = 3;</code>
       */
      public Builder clearLocationReport() {
        if (locationReportBuilder_ == null) {
          if (bodyCase_ == 3) {
            bodyCase_ = 0;
            body_ = null;
            onChanged();
          }
        } else {
          if (bodyCase_ == 3) {
            bodyCase_ = 0;
            body_ = null;
          }
          locationReportBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Person.LocationReport LocationReport = 3;</code>
       */
      public com.example.vertbuff.PersonProto.LocationReport.Builder getLocationReportBuilder() {
        return getLocationReportFieldBuilder().getBuilder();
      }
      /**
       * <code>.Person.LocationReport LocationReport = 3;</code>
       */
      public com.example.vertbuff.PersonProto.LocationReportOrBuilder getLocationReportOrBuilder() {
        if ((bodyCase_ == 3) && (locationReportBuilder_ != null)) {
          return locationReportBuilder_.getMessageOrBuilder();
        } else {
          if (bodyCase_ == 3) {
            return (com.example.vertbuff.PersonProto.LocationReport) body_;
          }
          return com.example.vertbuff.PersonProto.LocationReport.getDefaultInstance();
        }
      }
      /**
       * <code>.Person.LocationReport LocationReport = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.vertbuff.PersonProto.LocationReport, com.example.vertbuff.PersonProto.LocationReport.Builder, com.example.vertbuff.PersonProto.LocationReportOrBuilder> 
          getLocationReportFieldBuilder() {
        if (locationReportBuilder_ == null) {
          if (!(bodyCase_ == 3)) {
            body_ = com.example.vertbuff.PersonProto.LocationReport.getDefaultInstance();
          }
          locationReportBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.example.vertbuff.PersonProto.LocationReport, com.example.vertbuff.PersonProto.LocationReport.Builder, com.example.vertbuff.PersonProto.LocationReportOrBuilder>(
                  (com.example.vertbuff.PersonProto.LocationReport) body_,
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        bodyCase_ = 3;
        onChanged();;
        return locationReportBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Person.CommunicationMessage)
    }

    // @@protoc_insertion_point(class_scope:Person.CommunicationMessage)
    private static final com.example.vertbuff.PersonProto.CommunicationMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.vertbuff.PersonProto.CommunicationMessage();
    }

    public static com.example.vertbuff.PersonProto.CommunicationMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CommunicationMessage>
        PARSER = new com.google.protobuf.AbstractParser<CommunicationMessage>() {
      public CommunicationMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CommunicationMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CommunicationMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CommunicationMessage> getParserForType() {
      return PARSER;
    }

    public com.example.vertbuff.PersonProto.CommunicationMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_PersonReport_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_PersonReport_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_LocationReport_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_LocationReport_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_CommunicationMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_CommunicationMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Encapsulate.proto\022\006Person\"V\n\014PersonRep" +
      "ort\022\021\n\tperson_id\030\001 \001(\005\022\013\n\003age\030\002 \001(\005\022\016\n\006h" +
      "eight\030\003 \001(\003\022\026\n\016classification\030\004 \001(\t\"G\n\016L" +
      "ocationReport\022\023\n\013Location_id\030\001 \001(\005\022\t\n\001x\030" +
      "\002 \001(\003\022\025\n\rLocation_type\030\003 \001(\005\"\215\001\n\024Communi" +
      "cationMessage\022\r\n\005msgid\030\001 \001(\003\022,\n\014PersonRe" +
      "port\030\002 \001(\0132\024.Person.PersonReportH\000\0220\n\016Lo" +
      "cationReport\030\003 \001(\0132\026.Person.LocationRepo" +
      "rtH\000B\006\n\004bodyB\025\n\004testB\013PersonProtoP\000b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Person_PersonReport_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Person_PersonReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_PersonReport_descriptor,
        new java.lang.String[] { "PersonId", "Age", "Height", "Classification", });
    internal_static_Person_LocationReport_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Person_LocationReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_LocationReport_descriptor,
        new java.lang.String[] { "LocationId", "X", "LocationType", });
    internal_static_Person_CommunicationMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Person_CommunicationMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_CommunicationMessage_descriptor,
        new java.lang.String[] { "Msgid", "PersonReport", "LocationReport", "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
